---
# handlers file for lamp

- name: Reload httpd.
  ansible.builtin.systemd_service:
    name: httpd
    state: reloaded
  become: true

- name: Restart MariaDB.
  ansible.builtin.systemd_service:
    name: mariadb
    state: restarted
  become: true
